

class OptunaOptimRun:
    """Class that contains all info for the whole optimization using optuna for one model and dataset"""
    def __init__(self):
        self.study_name = ...
        self.save_path = ...
        self.storage = ...
        self.study = ...

